export const ROUTE_PATH = {
  home: "/",
  landing: "/landing",
  main: "/main",
  library: "/main/library",
  bookDetail: "/main/book-detail",
  chapter: "/main/chapter",
  newBook: "/main/new-book",
  bookClub: "/main/book-club",
  newBookClub: "/main/new-book-club",
  newGathering: "/main/new-gathering",
  myPage: "/main/my-page",
  join: "/join",
  auth: "/auth/:provider",
  signUp: "/sign-up",
  notFound: "404",
};
